[tool.black]
line-length = 88
target-version = ["py313"]

[tool.isort]
profile = "black"
src_paths = ["src", "scripts"]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "pep621"
update_changelog_on_bump = true
